version: 1.0.{build}
skip_tags: true
configuration: Debug
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

before_build:
  - nuget restore ".\NuBus.sln"
  - nuget install OpenCover -Version 4.6.166 -OutputDirectory .\NuBus\packages
  - nuget install coveralls.net -Version 0.6.0 -OutputDirectory .\NuBus\packages
  - nuget install NUnit.Runners -Version 3.6.0 -OutputDirectory .\NuBus\packages
  - choco install activemq --ignoredependencies -y
  - refreshenv
  - ps: $MyProcess = Start-Process -FilePath "C:\tools\ActiveMQ\apache-activemq-5.11.1\bin\activemq.bat" -ArgumentList "start" -PassThru
  #- start /B C:\tools\ActiveMQ\apache-activemq-5.11.1\bin\activemq start
  #- ps: (Get-Service -Name ActiveMQ).Status
  #- type C:\ProgramData\chocolatey\logs\chocolatey.log

build:
  project: .\NuBus.sln
  verbosity: minimal

test_script:
- ps: >-
    .\Nubus\packages\OpenCover.4.6.166\tools\OpenCover.Console.exe -register:user -target:.\NuBus\packages\NUnit.ConsoleRunner.3.6.0\tools\nunit3-console.exe "-targetargs:""NuBusTest\bin\$env:CONFIGURATION\NuBus.Test.dll"" " -filter:"+[NuBus]*" -output:opencoverCoverage.xml

    $coveralls = (Resolve-Path "NuBus/packages/coveralls.net.*/tools/csmacnz.coveralls.exe").ToString()
    
    $env:APPVEYOR_BUILD_NUMBER
    
    & $coveralls --opencover -i opencoverCoverage.xml --repoToken $env:COVERALLS_REPO_TOKEN --useRelativePaths --commitId $env:APPVEYOR_REPO_COMMIT --commitBranch $env:APPVEYOR_REPO_BRANCH --commitAuthor $env:APPVEYOR_REPO_COMMIT_AUTHOR --commitEmail $env:APPVEYOR_REPO_COMMIT_AUTHOR_EMAIL --commitMessage $env:APPVEYOR_REPO_COMMIT_MESSAGE --jobId $env:APPVEYOR_BUILD_NUMBER --serviceName appveyor
